### ISSUE TITLE
Hangman Game

### ISSUE THREAD

**Issue by JayantGoel001** [itsmedeepak/Hacktoberfest-2022#122]
Hi @itsmedeepak, 
**Is your feature request related to a problem? Please describe.**
I want to add a hangman game.

**Describe the solution you'd like**
Hangman is a guessing game for two or more players. One player thinks of a word, phrase or sentence and the other tries to guess it by suggesting letters within a certain number of guesses.

**Comment by itsmedeepak** [comment]
Explain your Issue
